# Generated by Django 4.2.9 on 2024-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_rename_sites_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_url',
            field=models.URLField(max_length=255),
        ),
    ]
