# Generated by Django 4.2.9 on 2024-02-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
