# Generated by Django 4.2.9 on 2024-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='url_test',
            field=models.URLField(blank=True),
        ),
    ]
