# Generated by Django 4.2.9 on 2024-02-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_site_url_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='url_test',
        ),
    ]
